---
name: 'Panoptes Base #1'
site: # Mauna Loa Observatory
    lat: '19:32:09.3876'
    lon: '-155:34:34.3164'
    elevation: 3400.0
mount:
    model: ioptron
    port: '/dev/ttyUSB0'
cameras:
    - 
        model: canon
        port: 'usb:001,014'
    - 
        model: canon
        port: 'usb:001,013'     
log:
    dir: '/var/log/Panoptes/'
    file: 'panoptes.log'