---
name: 'Panoptes Base #1'
site: # Mauna Loa Observatory
    lat: 19.54
    lon: -155.58
    elevation: 3400.0
    gmt_offset: -600
    horizon: 10
    twilight_horizon: -12
base_dir: '/var/panoptes/'
image_dir: '/var/panoptes/images'
webcam_dir: '/var/panoptes/images/webcams'
environment:
    computer_box:
        serial_port: '/dev/ttyACM0'
    camera_box:
        serial_port: '/dev/ttyACM1'
mount:
    model: ioptron
    port: '/dev/ttyUSB0'
    connect_on_startup: False
    park_position:
        alt: '-67:32:33'
        az: '027:06:11'
cameras:
    -
        model: canon
        port: 'usb:001,014'
        connect_on_startup: False
    -
        model: canon
        port: 'usb:001,013'
        connect_on_startup: False
webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
state_machine: simple_state_table
log:
    dir: '/var/panoptes/logs/Panoptes/'
    file: 'panoptes.log'
