---
name: 'PAN 001'
location:
    name: Mauna Loa Observatory
    latitude: 19.54
    longitude: -155.58
    elevation: 3400.0
    gmt_offset: -600 # Minutes
    horizon: 18
    twilight_horizon: -12
    timezone: 'US/Hawaii'
base_dir: '/var/panoptes/POCS'
image_dir: '/var/panoptes/images'
webcam_dir: '/var/panoptes/webcams'
data_dir: '/var/panoptes/data'
resources_dir: '/var/panoptes/POCS/resources/'
log_dir: '/var/panoptes/logs'
log_file: 'panoptes.log'
web_interface: true,
targets_file: 'default_targets.yaml'
environment:
    computer_box:
        serial_port: '/dev/ttyACM0'
    camera_box:
        serial_port: '/dev/ttyACM1'
mount:
    model: ioptron
    port: '/dev/ttyUSB0'
    connect_on_startup: False
    park_position:
        alt: '-67:32:33'
        az: '027:06:11'
weather:
    station: mongo
    aag_cloud:
        serial_port: '/dev/ttyUSB0'
        threshold_cloudy: -20.
        threshold_very_cloudy: -15.
        threshold_windy: 20.
        threshold_very_windy: 30.
        threshold_gusty: 40.
        threshold_very_gusty: 50.
        threshold_rainy: 230.
        safety_delay: 15 ## minutes
        heater:
            low_temp: 0 ## deg C
            low_delta: 6 ## deg C
            high_temp: 20 ## deg C
            high_delta: 4 ## deg C
            min_power: 10 ## percent
            impulse_temp: 10 ## deg C
            impulse_duration: 60 ## seconds
            impulse_cycle: 600 ## seconds
cameras:
    -
        model: canon_indi
        port: 'usb:001,014'
        connect_on_startup: False
    -
        model: canon_indi
        port: 'usb:001,013'
        connect_on_startup: False
messaging:
    port: 6500
webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
state_machine: simple_state_table
