---
name: 'PAN 001'
site:
    name: Mauna Loa Observatory
    lat: 19.54
    lon: -155.58
    elevation: 3400.0
    gmt_offset: -600 # Minutes
    horizon: 10
    twilight_horizon: -12
base_dir: '/var/panoptes/POCS'
image_dir: '/var/panoptes/images'
webcam_dir: '/var/panoptes/webcams'
data_dir: '/var/panoptes/data'
log_dir: '/var/panoptes/logs'
conf_files_dir: '/var/panoptes/POCS/conf_files/'
targets: 'default_targets.yaml'
environment:
    computer_box:
        serial_port: '/dev/ttyACM0'
    camera_box:
        serial_port: '/dev/ttyACM1'
mount:
    model: ioptron
    port: '/dev/ttyUSB0'
    connect_on_startup: False
    park_position:
        alt: '-67:32:33'
        az: '027:06:11'
weather:
    aag_cloud:
        serial_port: '/dev/ttyUSB1'
        threshold_cloudy: 0.
        threshold_very_cloudy: 0.
        threshold_windy: 0.
        threshold_very_windy: 0.
        threshold_gusty: 0.
        threshold_very_gusty: 0.
        threshold_rainy: 0.
cameras:
    -
        model: canon
        port: 'usb:001,014'
        connect_on_startup: False
    -
        model: canon
        port: 'usb:001,013'
        connect_on_startup: False
messaging:
    port: 6500
webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
state_machine: simple_state_table
