webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
directories:
    images: '/var/panoptes/images'
    webcam: '/var/panoptes/webcams'
    data: '/var/panoptes/data'
environment:
    camera_box:
        serial_port: '/dev/ttyACM0'
weather:
    station: mongo
    aag_cloud:
        serial_port: '/dev/ttyUSB1'
        threshold_cloudy: -30
        threshold_very_cloudy: -15.
        threshold_windy: 50.
        threshold_very_windy: 75.
        threshold_gusty: 100.
        threshold_very_gusty: 125.
        threshold_wet: 2000.
        threshold_rainy: 1700.
        safety_delay: 5 ## minutes
        heater:
            low_temp: 0 ## deg C
            low_delta: 6 ## deg C
            high_temp: 20 ## deg C
            high_delta: 4 ## deg C
            min_power: 10 ## percent
            impulse_temp: 10 ## deg C
            impulse_duration: 60 ## seconds
            impulse_cycle: 600 ## seconds