---
name: 'Generic PANOPTES Unit'
location:
    name: Mauna Loa Observatory
    latitude: 19.54
    longitude: -155.58
    elevation: 3400.0
    utc_offset: -10.00 # Hours
    horizon: 18
    twilight_horizon: -12
    timezone: 'US/Hawaii'
directories:
    base: '/var/panoptes/POCS'
    images: '/var/panoptes/images'
    webcam: '/var/panoptes/webcams'
    data: '/var/panoptes/data'
    resources: '/var/panoptes/POCS/resources/'
    targets: '/var/panoptes/POCS/resources/conf_files/targets'
scheduler:
    type: 'simple'
    targets_file: 'simple.yaml'
environment:
    computer_box:
        serial_port: '/dev/ttyACM0'
    camera_box:
        serial_port: '/dev/ttyACM1'
mount:
    model: ioptron
    port: '/dev/ioptron_mount'
cameras:
    -
        model: canon_gphoto2
        port: 'usb:003,006'
    -
        model: canon_gphoto2
        port: 'usb:002,010'
weather:
    station: mongo
    aag_cloud:
        serial_port: '/dev/ttyUSB0'
        threshold_cloudy: -20.
        threshold_very_cloudy: -15.
        threshold_windy: 20.
        threshold_very_windy: 30.
        threshold_gusty: 40.
        threshold_very_gusty: 50.
        threshold_rainy: 230.
        safety_delay: 15 ## minutes
        heater:
            low_temp: 0 ## deg C
            low_delta: 6 ## deg C
            high_temp: 20 ## deg C
            high_delta: 4 ## deg C
            min_power: 10 ## percent
            impulse_temp: 10 ## deg C
            impulse_duration: 60 ## seconds
            impulse_cycle: 600 ## seconds
messaging:
    port: 6500
webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
state_machine: simple_state_table
logger:
    version: 1
    use_utc: True
    formatters:
      simple:
        format: '%(asctime)s UTC - %(message)s'
        datefmt: '%H:%M:%S'
      detail:
        format: '%(processName)s(%(process)d) %(threadName)s %(asctime)14s UTC %(levelname)8s %(module)20s:%(lineno)4d:%(funcName)-25s %(message)s'
        datefmt: '%Y%M%S%H%M%S'

    loggers:
      all:
        handlers: [all]
        propagate: true
      warn:
        handlers: [warn]
        propagate: true
      tornado:
        handlers: [all]
        propagate: false

    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
      all:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: detail
        when: W6
        backupCount: 4
        filename: /var/panoptes/logs/panoptes.log
      warn:
        class: logging.handlers.TimedRotatingFileHandler
        level: WARNING
        formatter: detail
        when: W6
        backupCount: 4
        filename: /var/panoptes/logs/warnings.log

    root:
      level: DEBUG
      handlers: [console, all, warn]
      propagate: true