---
name: 'Panoptes Base #1'
site: # Mauna Loa Observatory
    lat: '19:32:09.3876'
    lon: '-155:34:34.3164'
    elevation: 3400.0
    gmt_offset: -10
camera_box:
    port: '/dev/ttyACM0'
mount:
    model: ioptron
    port: '/dev/ttyUSB0'
    connect_on_startup: False
cameras:
    -
        model: canon
        port: 'usb:001,014'
        connect_on_startup: False
    -
        model: canon
        port: 'usb:001,013'
        connect_on_startup: False
state_machine: simple_state_table
log:
    dir: '/var/log/Panoptes/'
    file: 'panoptes.log'