version: '3.7'
services:
  config-server:
    image: gcr.io/panoptes-exp/panoptes-utils:develop
    deploy:
      mode: global
    init: true
    tty: true
    container_name: config-server
    hostname: config-server
    network_mode: host
    env_file:
      - env
    command: [ "panoptes-config-server --verbose run --config-file /app/config.yaml" ]
    volumes:
      - type: bind
        source: "${PANOPTES_CONFIG_FILE}"
        target: /app/config.yaml
  pocs-control:
    image: gcr.io/panoptes-exp/panoptes-pocs:develop
    deploy:
      mode: global
    init: true
    container_name: pocs-control
    hostname: pocs-control
    privileged: true
    network_mode: host
    env_file:
      - env
    volumes:
      - logdir:/logs
    command: [ "wait-for-it ${PANOPTES_CONFIG_PORT}:${PANOPTES_CONFIG_PORT} -- /bin/bash" ]
volumes:
  logdir:
    driver: local
    driver_opts:
      type: none
      device: "${PANLOG:-${PWD}/logs}"
      o: bind
